---
title: "Day 2: data management"
author: "Sarah Strochak (HFPC)"
date: "`r format(Sys.time(), '%B %d, %Y %H:%M')`"
output:
  html_document:
    number_sections: TRUE
    self_contained: TRUE
    code_folding: hide
    toc: TRUE
    toc_float: TRUE
    css: ../www/web_report.css
    editor_options:
      chunk_output_type: console
---

<style>
@import url('https://fonts.googleapis.com/css?family=Lato&display=swap');
</style>

<link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">

# Review

* assignment operator
* functions
* tidy data

# Motivation 

"The toughest part of data visualization is data munging."
- Aaron Williams

# Primary functions

* `select()`
* `rename()`
* `filter()`
* `arrange()`
* `mutate()`
* `summarize()`
* `group_by()`

All of these functions have the same structure.

1. The first argument is the dataframe
2. The subsequent arguments describe what to do with the data frame, using the variable names (without quotes).
3. The result is a new data frame.

Source: [R for data science](https://r4ds.had.co.nz/transform.html)


# The pipe operator


# Exercise 0

If you are using a different computer or didn't attend last Friday's session, follow steps 1 and 2. If not- skip to step 3.

<font color="#55b748">**Step 1:**</font> Create a new directory called `urbn101`

<font color="#55b748">**Step 2:**</font> Open RStudio. Click "Project: (None)" in the top right corner. Click "New Project" and create a project based on the existing `urbn101` directory.

<font color="#55b748">**Step 3:**</font> Open a `.R` script with the button in the top left. Save the script as `02_data-management.R`.

<font color="#55b748">**Step 4:**</font> If you have not previously installed `library(tidyverse)`: submit `install.packages("tidyverse")` to the Console.

<font color="#55b748">**Step 5:**</font> Write `library(tidyverse)` at the top of `02_data-management.R`. With the cursor on the line of text, click Control-Enter.


# Exercise 1

<font color="#55b748">**Step 1:**</font> Assign the `storms` dataset to be called storms. Submit `View(storms)` in the console.



You can also deselect specific columns in your data by using the `-` operator

<font color="#55b748">**Step 2:**</font> Create a new dataset with all the variables except for `ts_diameter` and `hu_diameter`, by using `select` and `-`.

<font color="#ec008b">**Select**</font>

`select()` is used when you want to limit the number of **columns** in your dataframe. The arguments after the dataframe should be names of columns, without quotes.
For example:

```
  select(dataset, col1, col2)
```

<font color="#55b748">**Step 3:**</font> Create a new dataset that only category 5 storms using  `filter()`.


<font color="#ec008b">**Filter**</font>

`filter()` is used when you want to filter to specific rows in your dataframe, based on certain conditions. Filter works with the following comparison operators:

  - `<`, `>`, `<=`, `>=`
  - `==`, `!=`

You can also chain together multiple condtions with `&` (and) or `|` (or). The arguments after the dataframe should be conditions you want to filter your dataset on. For example

```
filter(dataset, col1 > 0)
```



<font color="#55b748">**Step 4:**</font> Chain all three of these commands together with the `%>%` operator. Then rename the column `pressure` to `air_pressure`.

<font color="#ec008b">**%>%**</font>

The pipe operator allows you to string together a set of different functions.
The first argument in the next function you are using will be replaced with what precedes `%>%`


<font color="#ec008b">**Rename**</font>

The syntax for rename is:

```
dataset %>% 
  rename(new_name = current_name)
```

This same syntax can be used inside `select()`, and you can rename and select variables simultanously.
 
<font color="#55b748">**Step 5:**</font> `wind` is measured in knots. Convert `wind` into miles per hour. Each knot is equal to 1.15078 miles per hour.

<font color="#ec008b">**Mutate**</font>

`mutate()` can make new variables and edit existing variables. New variables are always added to the end of the dataframe. You can use arithmetic arguments, such as `+`, `-`, `*`, `/`, and `^`. The syntax for mutate is:

```
dataset %>% 
  mutate(new_column = 100 * other_column)
```


<font color="#55b748">**Step 6:**</font> Use `summarize()` to find the average wind speed (in MPH) of a category 5 storm.

<font color="#ec008b">**Summarize**</font>

`summarize` computes summary statistics for as set of observations in your data. The syntax is:

```
dataset %>% 
  mutate(max = max(other_column))
```
<font color="#55b748">**Step 7:**</font> Make a dataset with storms that occured in the summer (June, July, August).

<font color="#ec008b">**The `%in%` operator**</font>

The `%in%` operator is useful for filtering based on more than one option within one variable. 

```
filter(dataset, var1 == "a" | var1 == "b" | var1 == "c")
```

is equivalent to 

```
filter(dataset, var1 %in% c("a", "b", "c"))
```


# Exercise 2 

<font color="#55b748">**Step 1:**</font> Use the `txhousing` dataset. Assign the dataset to an object in your global environment named `tx_housing`.

<font color="#55b748">**Step 2:**</font> Compute a new variable, `average_price` by dividing `volume` by `sales`.

<font color="#55b748">**Step 3:**</font> Use `if_else()` to create a variable called `flag` that is 1 if the average sales price is larger than the median sales price.

<font color="#ec008b">**If/then logic**</font>

`if_else()` is an important tool in combination with `mutate()`. It employs if-then logic: the first argument is a binary statement. The second statement says what to do if the first argument is evaluated to `TRUE`- the third is what to do if it is `FALSE` This is particularly useful for creating dummy or indicator variables.
When you have more than two possible outcomes, it is more efficient to use `case_when()`.

<font color="#55b748">**Step 3a:**</font> Type `?case_when` into the console.

<font color="#55b748">**Step 4:**</font> Type the following code into your script.

```
tx_housing %>% 
  group_by(year) %>% 
  summarize(yearly_sales = sum(sales))
```

<font color="#ec008b">**Group By**</font>

`group_by` groups your dataframe into discrete categories. It can be very powerful when used with `summarize`


<font color="#55b748">**Step 5:**</font> Add the argument `na.rm = TRUE` to the `sum()` function and rerun the code. Add a comment to explain the code.

<font color="#55b748">**Step 6:**</font> Sort the results of the previous code in order from most to least sales by adding ` %>% arrange(desc(yearly_sales))` to the end of the code.

<font color="#55b748">**Step 7a:**</font> Which county had the most home sales in January 2008? (Hint: use `filter()` and `arrange()`).

<font color="#55b748">**Step 7b:**</font> Which county had the least home sales in 2006? (Hint: group by the county and the year- then use `summarize()`).

<font color="#55b748">**BONUS:**</font> Plot the number of annual home sales over time!


# Exercise 3

<font color="#55b748">**Step 1:**</font> Use the `starwars` dataframe. Type `count(starwars, homeworld)` into your script.

<font color="#55b748">**Step 2:**</font> Repeat the first exercise, but first filter out any characters that have a missing `homeworld`.

<font color="#55b748">**Step 3:**</font> Find the average and median height and mass for humans vs. droids. (Hint: use `group_by()` and `summarize()`). Make sure that you are correcting for observations with missing values!

<font color="#55b748">**Step 4:**</font> Make a dummy variable called `droid` that is `1` for droids and `0` for humans. Make a variable called `tall` that is `1` if the characters are more than 200 cm tall. How many tall humans are there? 

<font color="#55b748">**Step 5:**</font> What is the most common skin color for droids? 



# Resources

* [R for Data Science: data transformation](https://r4ds.had.co.nz/transform.html)
* [Data wrangling cheat sheet](https://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf)
