project:
  type: book
  output-dir: ../docs

book:
  title: "Intro to R"
  author: "Amy Rogin and Aaron R. Williams"
  date: today
  chapters:
    - index.qmd
    - 01_lesson.qmd
    - 02_lesson.qmd
    - 03_lesson.qmd
    - 04_lesson.qmd
    - 05_lesson.qmd
    - 06_lesson.qmd

bibliography: references.bib

format:
  html:
    css: style.scss
